FROM nginx:alpine

# Copy nginx configuration
COPY docker/nginx.conf /etc/nginx/nginx.conf

# Copy static files
COPY frontend/dist /usr/share/nginx/html

# Fix file permissions for nginx
RUN chmod -R 644 /usr/share/nginx/html/* && \
    chmod 755 /usr/share/nginx/html

# Expose ports
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
